version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    stdin_open: true
    ports:
      - 80:80
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - backend-network

networks:
  backend-network:
    external:
      name: backend_network
